//! Connective elements (связки).
//!
//! Connectives are auxiliary elements that link functions together in a tale.
//! Propp emphasizes that these are highly variable and often interchangeable.
//! The actual text is generated by LLM; we only provide structural hints.

use serde::{Deserialize, Serialize};

use crate::tale::Moment;

/// Connective element between moments (связка между моментами).
///
/// These are not exhaustive — Propp notes their variability.
/// The actual text will be generated by LLM.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Connective {
    /// Motivation for action (мотивировка действия).
    /// Examples: revenge, desire, duty, curiosity, need, poverty, etc.
    Motivation(String),
    /// Mode of spatial transference (способ перемещения).
    /// Examples: walking, flying, riding, magical transport, etc.
    Transference(String),
    /// Temporal transition (временной переход).
    /// Examples: "immediately", "next day", "долго ли, коротко ли", etc.
    Temporal(String),
    /// Custom connective for LLM-generated content.
    Custom(String),
}

impl Connective {
    /// Create a motivation connective.
    #[must_use]
    pub fn motivation(text: impl Into<String>) -> Self {
        Self::Motivation(text.into())
    }

    /// Create a transference connective.
    #[must_use]
    pub fn transference(text: impl Into<String>) -> Self {
        Self::Transference(text.into())
    }

    /// Create a temporal connective.
    #[must_use]
    pub fn temporal(text: impl Into<String>) -> Self {
        Self::Temporal(text.into())
    }

    /// Create a custom connective.
    #[must_use]
    pub fn custom(text: impl Into<String>) -> Self {
        Self::Custom(text.into())
    }
}

/// Triplication (утроение) — repetition of an episode three times.
///
/// One of the most characteristic features of fairy tales.
/// The third attempt is usually successful or climactic.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Triplication {
    /// The repeated moments.
    pub moments: Vec<Moment>,
    /// Variation pattern description (for LLM guidance).
    /// Examples: "identical", "ascending difficulty", "third succeeds"
    pub variation: String,
}

impl Triplication {
    /// Create a new triplication.
    #[must_use]
    pub fn new(moments: Vec<Moment>, variation: impl Into<String>) -> Self {
        Self {
            moments,
            variation: variation.into(),
        }
    }

    /// The number of repetitions (always 3 in classic fairy tales).
    #[must_use]
    pub const fn count(&self) -> usize {
        3
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_connective_flexibility() {
        // Connectives can be any text - they're hints for LLM
        let c1 = Connective::motivation("из любопытства");
        let c2 = Connective::temporal("долго ли, коротко ли");
        let c3 = Connective::transference("на ковре-самолёте");

        assert!(matches!(c1, Connective::Motivation(_)));
        assert!(matches!(c2, Connective::Temporal(_)));
        assert!(matches!(c3, Connective::Transference(_)));
    }

    #[test]
    fn test_triplication() {
        let trip = Triplication::new(vec![], "третья попытка успешна");
        assert_eq!(trip.count(), 3);
        assert_eq!(trip.variation, "третья попытка успешна");
    }
}
