//! Dramatis personae (действующие лица).
//!
//! Characters in fairy tales are defined by their spheres of action,
//! not by their individual traits. One character may fulfill multiple spheres,
//! or one sphere may be distributed among several characters.
//!
//! Actual character attributes (names, appearance, etc.) are generated by LLM
//! based on the structural role defined here.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::Lang;

/// Unique identifier for a persona within a tale.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PersonaId(pub u32);

impl From<u32> for PersonaId {
    fn from(id: u32) -> Self {
        Self(id)
    }
}

/// Sphere of action (сфера действия / круг действий).
///
/// According to Propp, there are seven spheres of action that define
/// the structural roles characters play. One character may combine
/// multiple spheres, or one sphere may be distributed among several characters.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Sphere {
    /// Hero-seeker or hero-victim (герой-искатель или герой-жертва).
    Hero,
    /// Villain/antagonist (вредитель/антагонист).
    Villain,
    /// Donor/provider (даритель/снабдитель).
    Donor,
    /// Magical helper (волшебный помощник).
    Helper,
    /// Princess and her father (царевна и её отец).
    Princess,
    /// Dispatcher (отправитель).
    Dispatcher,
    /// False hero (ложный герой).
    FalseHero,
}

impl Sphere {
    /// All spheres of action.
    pub const ALL: [Sphere; 7] = [
        Sphere::Hero,
        Sphere::Villain,
        Sphere::Donor,
        Sphere::Helper,
        Sphere::Princess,
        Sphere::Dispatcher,
        Sphere::FalseHero,
    ];

    /// Display name of the sphere.
    #[must_use]
    pub const fn name(&self, lang: Lang) -> &'static str {
        match lang {
            Lang::En => match self {
                Sphere::Hero => "Hero",
                Sphere::Villain => "Villain",
                Sphere::Donor => "Donor",
                Sphere::Helper => "Helper",
                Sphere::Princess => "Princess",
                Sphere::Dispatcher => "Dispatcher",
                Sphere::FalseHero => "False Hero",
            },
            Lang::Ru => match self {
                Sphere::Hero => "Герой",
                Sphere::Villain => "Вредитель",
                Sphere::Donor => "Даритель",
                Sphere::Helper => "Помощник",
                Sphere::Princess => "Царевна",
                Sphere::Dispatcher => "Отправитель",
                Sphere::FalseHero => "Ложный герой",
            },
        }
    }
}

/// Character attributes (атрибуты персонажа).
///
/// Propp notes that characters have attributes (nomenclature, appearance, etc.)
/// but these are independent of the morphological structure.
/// This is a flexible key-value store for LLM-generated content.
pub type Attributes = HashMap<String, String>;

/// A character in the tale (персонаж сказки).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Persona {
    /// Unique identifier within the tale.
    pub id: PersonaId,
    /// Spheres of action (сферы действия).
    pub spheres: Vec<Sphere>,
    /// Character attributes (атрибуты) — filled by LLM.
    pub attributes: Attributes,
}

impl Persona {
    /// Create a new persona with given ID and spheres.
    #[must_use]
    pub fn new(id: impl Into<PersonaId>, spheres: Vec<Sphere>) -> Self {
        Self {
            id: id.into(),
            spheres,
            attributes: HashMap::new(),
        }
    }

    /// Set attributes.
    #[must_use]
    pub fn with_attributes(mut self, attributes: Attributes) -> Self {
        self.attributes = attributes;
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_persona_with_multiple_spheres() {
        // A character can combine multiple spheres (e.g., hero who is also dispatcher)
        let persona = Persona::new(1u32, vec![Sphere::Hero, Sphere::Dispatcher]);
        assert_eq!(persona.spheres.len(), 2);
        assert!(persona.spheres.contains(&Sphere::Hero));
        assert!(persona.spheres.contains(&Sphere::Dispatcher));
    }

    #[test]
    fn test_attributes_flexibility() {
        let mut attrs: Attributes = HashMap::new();
        attrs.insert("name".to_string(), "Иван".to_string());
        attrs.insert("epithet".to_string(), "дурак".to_string());
        attrs.insert("appearance".to_string(), "молодой крестьянин".to_string());

        assert_eq!(attrs.get("name").map(String::as_str), Some("Иван"));
        assert_eq!(attrs.get("epithet").map(String::as_str), Some("дурак"));
        assert_eq!(attrs.get("custom_field"), None);
    }
}
