//! Tale structure (структура сказки).
//!
//! A fairy tale consists of an optional initial situation followed by one or more moves.
//! Each move is a sequence of moments (functions with participants).
//!
//! The actual narrative text is generated by LLM based on this structure.

use serde::{Deserialize, Serialize};

use crate::connective::Connective;
use crate::dramatis::{Persona, PersonaId};
use crate::function::NarrativeFunctionInstance;

/// A complete tale (сказка).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tale {
    /// Initial situation (начальная ситуация) — optional per Propp.
    pub initial: Option<InitialSituation>,
    /// One or more moves (ходы).
    pub moves: Vec<Move>,
    /// All personae in the tale.
    pub personae: Vec<Persona>,
}

impl Tale {
    /// Create a new tale with optional initial situation.
    #[must_use]
    pub fn new(initial: Option<InitialSituation>) -> Self {
        Self {
            initial,
            moves: Vec::new(),
            personae: Vec::new(),
        }
    }

    /// Get all moments across all moves.
    pub fn all_moments(&self) -> impl Iterator<Item = &Moment> {
        self.moves.iter().flat_map(|m| m.moments.iter())
    }
}

impl Default for Tale {
    fn default() -> Self {
        Self::new(None)
    }
}

/// Initial situation (начальная ситуация, "i" in Propp's notation).
///
/// Per Propp, this typically includes family enumeration and state of prosperity,
/// but both are optional. Some tales start directly with a function.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct InitialSituation {
    /// Setting description (for LLM).
    pub setting: Option<Setting>,
    /// Any additional context (for LLM).
    pub context: Option<String>,
}

impl InitialSituation {
    /// Create a new initial situation.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the setting.
    #[must_use]
    pub fn with_setting(mut self, setting: Setting) -> Self {
        self.setting = Some(setting);
        self
    }

    /// Set additional context.
    #[must_use]
    pub fn with_context(mut self, context: impl Into<String>) -> Self {
        self.context = Some(context.into());
        self
    }
}

/// Setting (место и время действия).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct Setting {
    /// Place description.
    pub place: Option<String>,
    /// Time description (often vague: "once upon a time").
    pub time: Option<String>,
}

impl Setting {
    /// Create a new setting.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the place.
    #[must_use]
    pub fn place(mut self, place: impl Into<String>) -> Self {
        self.place = Some(place.into());
        self
    }

    /// Set the time.
    #[must_use]
    pub fn time(mut self, time: impl Into<String>) -> Self {
        self.time = Some(time.into());
        self
    }
}

/// Move (ход) — a sequence from complication to resolution.
///
/// A tale can have one or more moves. Multiple moves can be:
/// - Sequential (one after another)
/// - Embedded (nested within another move)
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Move {
    /// Sequence of moments.
    pub moments: Vec<Moment>,
    /// Relation to previous move (связь с предыдущим ходом).
    pub relation: MoveRelation,
}

impl Move {
    /// Create a new initial move.
    #[must_use]
    pub fn new() -> Self {
        Self {
            moments: Vec::new(),
            relation: MoveRelation::Initial,
        }
    }

    /// Create a continuation move.
    #[must_use]
    pub fn continuation() -> Self {
        Self {
            moments: Vec::new(),
            relation: MoveRelation::Continuation,
        }
    }

    /// Create an embedded move.
    #[must_use]
    pub fn embedded() -> Self {
        Self {
            moments: Vec::new(),
            relation: MoveRelation::Embedded,
        }
    }

    /// Add a function as a moment.
    pub fn add_function(&mut self, function: impl Into<NarrativeFunctionInstance>) {
        self.moments.push(Moment::new(function.into()));
    }
}

impl Default for Move {
    fn default() -> Self {
        Self::new()
    }
}

/// Relation between moves (связь между ходами).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
pub enum MoveRelation {
    /// First move (первый ход).
    #[default]
    Initial,
    /// Continuation after Rs (продолжение).
    Continuation,
    /// Embedded/nested move (вложенный ход).
    Embedded,
}

/// Moment (момент) — a function with participants and connective.
///
/// A moment represents one function being performed, along with
/// information about who performs it and who is affected.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Moment {
    /// The function instance.
    pub function: NarrativeFunctionInstance,
    /// Who performs the function (кто выполняет).
    pub agent: Option<PersonaId>,
    /// Whom it affects (на кого направлено).
    pub patient: Option<PersonaId>,
    /// Connective to previous moment (связка).
    pub connective: Option<Connective>,
}

impl Moment {
    /// Create a new moment.
    #[must_use]
    pub fn new(function: NarrativeFunctionInstance) -> Self {
        Self {
            function,
            agent: None,
            patient: None,
            connective: None,
        }
    }

    /// Set the agent.
    #[must_use]
    pub fn with_agent(mut self, agent: PersonaId) -> Self {
        self.agent = Some(agent);
        self
    }

    /// Set the patient.
    #[must_use]
    pub fn with_patient(mut self, patient: PersonaId) -> Self {
        self.patient = Some(patient);
        self
    }

    /// Set the connective.
    #[must_use]
    pub fn with_connective(mut self, connective: Connective) -> Self {
        self.connective = Some(connective);
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::function::NarrativeFunction;

    #[test]
    fn test_tale_without_initial_situation() {
        // Some tales start directly with a function, per Propp
        let tale = Tale::new(None);
        assert!(tale.initial.is_none());
    }

    #[test]
    fn test_move_with_functions() {
        let mut m = Move::new();
        m.add_function(NarrativeFunction::Villainy);
        m.add_function(NarrativeFunction::Departure);
        assert_eq!(m.moments.len(), 2);
    }

    #[test]
    fn test_tale_all_moments() {
        let mut tale = Tale::default();

        let mut m1 = Move::new();
        m1.add_function(NarrativeFunction::Villainy);
        m1.add_function(NarrativeFunction::Departure);
        tale.moves.push(m1);

        let mut m2 = Move::continuation();
        m2.add_function(NarrativeFunction::Return);
        tale.moves.push(m2);

        assert_eq!(tale.all_moments().count(), 3);
    }
}
